### ISSUE TITLE
Custom Schema

### ISSUE THREAD

**Issue by miamilabs** [clayrisser/docker-openldap#2]
Great Work what you done.

I did try for hours now search on bitnami (i found similar issue but the solution did not work) so i hope you can help me here.

I am trying to add this schema : https://github.com/variablenix/ldap-mail-schema/blob/master/postfix-book.schema
but for some reason it wont get recognized.

I did put the schema in the folder "/data/openldapv2/conf/custom" 

```
services:
  openldap:
    image: registry.gitlab.com/bitspur/rock8s/docker-openldap:latest
    container_name: openldap
    ports:
      - '389:389'
      - '636:636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=supersecretpass!
      - LDAP_ROOT=dc=test,dc=in,dc=ua
      - LDAP_PORT_NUMBER=389
      - LDAP_LDAPS_PORT_NUMBER=636
      - BITNAMI_DEBUG=true
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/openldapCA.crt
      - LDAP_CUSTOM_SCHEMA_DIR=/custom-schemas
    volumes:
      - ./data/openldapv2/storage/openldap_data:/bitnami/openldap:rw
      - ./data/openldapv2/conf/cert:/opt/bitnami/openldap/certs:ro
      - ./data/openldapv2/conf/custom:/custom-schemas:rw

    domainname: "test.in.ua"
    hostname: "openldap"
    networks:
      - openldap
```
  
  This is only one output of the logs which i found.    
```
openldap  |  17:05:55.97 INFO  ==> Adding custom schemas : /custom-schemas ...
openldap  | 64e4eaf3 daemon: shutdown requested and initiated.
openldap  | 64e4eaf3 slapd shutdown: waiting for 0 operations/tasks to finish     
``` 
      
      
I am not LDAP expert, sorry if i am doing something wront but i took a lot of time to check bitnami repo.
      
 Thank you
