### ISSUE TITLE
Hash variable does not apply

### ISSUE THREAD

**Issue by thesefer** [clayrisser/docker-openldap#6]
Default docker-compose.yml

```
version: "3.7"

services:
  openldap:
    container_name: ${NAME}
    image: ${IMAGE}:latest
    hostname: openldap
    ports:
      - 389:1389
    environment:
      LDAP_ADMIN_PASSWORD: P@ssw0rd
      LDAP_HASH_PASSWORD: SHA512CRYPT
      LDAP_USERS: "user1,user2"
      LDAP_PASSWORDS: "pass1,pass2"
      LDAP_SKIP_DEFAULT_TREE: "no"
    volumes:
      - openldap:/bitnami/openldap
volumes:
  openldap: {}
```

`docker exec OpenLDAP slapcat -F /bitnami/openldap/slapd.d`
results in a base64 encoded password: `userPassword:: cGFzczI=`

Which means `LDAP_HASH_PASSWORD` does not apply. Let's check `/opt/bitnami/openldap/migrations/ppolicy.ldif`
```
olcPasswordHash: {CRYPT}
```

How to properly setup a running container using your example? I tried adding `LDAP_EXTRA_SCHEMAS` and mounting the folders in `context` to no avail. A proper initial documentation would be appreciated and a full documentation for what your image supports and how to use it there.

Trying to add a user using phpLDAPadmin shows the following error:

```
Template Value Error
--
This template uses a selection list for attribute [gidNumber], however the selection list is empty.You may need to create some dependancy entries in your LDAP server so that this attribute renders with values. Alternatively, you may be able to define the appropriate selection values in the template file.
```
